### ISSUE TITLE
Add a `role` header to the SWAP REQUEST

### ISSUE THREAD

**Issue by bonomat** [comit-network/RFCs#107]
Currently, the "cryptographic" role is implicitly tied to whoever sends the swap request: it defaults to Alice.

We want to add a header to the swap request that allows us to explicitly specify the role. This means the person responding to the swap request specifies the secret_hash.

**Comment by D4nte** [comment]
> At the moment Alice sends a swap request message to Bob, Bob accepts, Alice starts with funding, etc.
> 
> I propose to decouple the _swap request_ from the actual blockchain protocol for RFC003 and rename it (e.g _setup phase_).
> 
> This way, Alice and Bob could switch role with only sending one message, e.g. Alice does not generate the secret but asks Bob for it, now Bob will need to move first with the funding.

I'd be keen to keep our terminology as:
- Alice generates the secret
- Bob does not

So that your proposal would be for Bob to send the message first and ask for the hash to Alice.

**Comment by bonomat** [comment]
Closing this as this will go aways with the negotiation protocol changes.
