### ISSUE TITLE
Name of SWAP message

### ISSUE THREAD

**Issue by birnbuazn** [comit-network/RFCs#110]
## Open/unresolved questions

- [ ] Is `SWAP` really a good name for your message in financial terms? As far as I understood, you are rather doing "exchange"s (as in "currency exchange"). 

A swap is generally a (longer lasting) contract where additional properties (like an interest rate) are fixed: https://www.investopedia.com/terms/s/swap.asp

**Comment by thomaseizinger** [comment]
"SWAP" is short for "Atomic Swap" and does not refer to the financial term "swap".
