### ISSUE TITLE
Lack of symmetry when processing declined responses

### ISSUE THREAD

**Issue by birnbuazn** [comit-network/RFCs#111]
## Open/unresolved questions

- [ ] Why do you treat parsing of declined SWAP responses differently then accepted ones? In particular, why is there a shortcut when parsing a “decline” message? 

The protocol header should really be parsed for "declined" messages as well and the body of the message should be parsed accordingly.

Think about the following use case: What if somebody wants to extend the protocol and introduce something like “temporary declines”, where information is returned in the body. With your setup now there's no way to parse this info.

**Comment by thomaseizinger** [comment]
Hey @birnbuazn, 
thanks for the feedback!

If I understand you correctly, you would want to allow users to add new reasons for declining a SWAP request that allow them to pass some data? That is totally supported!
Simply define a new `DeclineBody`(https://github.com/comit-network/RFCs/blob/master/RFC-002-SWAP.md#the-type-declinebody-and-the-initial-set-of-possible-values) and include whatever data you want in the `details` object!

Hopefully, that answers your questions. Feel free to re-open this ticket if not :)
