### ISSUE TITLE
Data type for timestamps in HTLCs

### ISSUE THREAD

**Issue by birnbuazn** [comit-network/RFCs#113]
## Open/unresolved questions

- [ ] Small thing, but I would in general use u64 for Unix time stamps (instead of u32) to avoid year 2038 time problems in HTLCs.

**Comment by D4nte** [comment]
Thank you for your feedback.

We have taken in account and debated the `u32` vs `u64` debate and decided it did not matter as it would only impact from 2106.

Moreover all our contracts are one-use only so if someone where still to use COMIT and our code in 2106 then a quick patch would be enough to keep COMIT working.

However, you mentioned 2038 which is slightly earlier than what we thought.

The following except for Rust code gives me 2106. How did you come up with 2038?

```
use chrono::{TimeZone, Utc};

fn main() {
    let max = ::std::u32::MAX;
    let dt = Utc.timestamp(max.into(), 0);
    println!("{}", dt.to_rfc2822())
}
```
Output:
```
Process finished with exit code 0
```

**Comment by birnbuazn** [comment]
https://en.wikipedia.org/wiki/Year_2038_problem <https://en.wikipedia.org/wiki/Year_2038_problem>

--
Stefan Haberl
https://meine-praxis.org
https://ueberland.org

**Comment by D4nte** [comment]
> [en.wikipedia.org/wiki/Year_2038_problem](https://en.wikipedia.org/wiki/Year_2038_problem) <[en.wikipedia.org/wiki/Year_2038_problem](https://en.wikipedia.org/wiki/Year_2038_problem)>

Thanks! I had a hunch, the 2038 issue is for `signed 32-bit binary integers (`i32` in Rust).
We are using `unsigned 32-bit binary integers` (`u32` in Rust).

If I remember correctly, there is a reason why we use u32, due to some conversion issues with u64 but I cannot remember exactly on top of my head.

I'll keep open and we will try to tackle it and be sure to add appropriate documentation if it is not a trivial task.

**Comment by thomaseizinger** [comment]
Unfortunately, I don't think it is even in our hands to decide that.
Bitcoin for example uses a u32 for the `nLocktime` field so I don't think there is much we can do.

https://github.com/bitcoin/bitcoin/blob/master/src/primitives/transaction.h#L290
