### ISSUE TITLE
Establish a shared identifier for a swap as part of a swap request

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/RFCs#123]
Related to #121 but may also make sense regardless of that.

If we want to send more messages that refer to a past swap, both parties need a shared understanding of which swap they are referring to.

**Comment by thomaseizinger** [comment]
This was already implemented in https://github.com/comit-network/comit-rs/pull/1415, hence this ticket is about aligning the RFC with what the implementation does.

**Comment by bonomat** [comment]
@thomaseizinger : shall we close this in favor of the _new_ execution protocol: https://github.com/coblox/admin/issues/157

**Comment by thomaseizinger** [comment]
> @thomaseizinger : shall we close this in favor of the new execution protocol: [coblox/admin#157](https://github.com/coblox/admin/issues/157)

Can close it. Just to clarify though: we already implemented this, this ticket would just be about updating the RFC to say what we did.

**Comment by bonomat** [comment]
Thanks for the clarification. 
As discussed offline: once we have the new execution protocol the old RFC will be outdated. 
In the meantime, we are fine with having this rfc-mismatch.
