### ISSUE TITLE
Have a concise name for the cryptographic protocol described in RFC003

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/RFCs#130]
## Problem

On several occasions, we learned that "rfc003" is not a good name for a protocol. It is just not descriptive about _what_ the protocol actually does.
Now that we are starting to market COMIT, the names of protocols become public facing, hence they should be good. This will be a very impactful change but I think the added clarity is worth it.

Most importantly, if we go for https://github.com/comit-network/RFCs/issues/121, we are going to need a good name for the protocol string. `/comit/rfc003` is kind of odd because the protocol by itself would be described in a different RFC (maybe?).

## Goal

Have a concise name for the cryptographic protocol described in RFC003.
This is just about deciding on the name.

## Recommendation

- grab Thomas but don't grab self!
- Take a whiteboard and list all important key words that make up the protocol (e.g. HTLCs, 2 party, 4 transactions, etc)
- Make up a sentence or a phrase that describes the protocol
- Reorder the phrase until you can form a good-sounding acronym from the initial letters of the words.
- Don't create a spike doc about it

**Comment by bonomat** [comment]
https://www.fantasynamegenerators.com/ancient-greek-names.php

**Comment by D4nte** [comment]
Also drop the "swap" terminology, or at least, do not include in this name and drop it slowly?

**Comment by bonomat** [comment]
If I remember correctly, we said some time ago we want to wait for the next protocol before we rename it so that we don't get a clash with the meaning of the acronym. 

If 
> Now that we are starting to market COMIT, the names of protocols become public facing, hence they should be good. This will be a very impactful change but I think the added clarity is worth it.

is a main concern, then I propose to consult the marketing team before making a final decision.

**Comment by thomaseizinger** [comment]
> consult the marketing team before making a final decision.

The TenX marketing team? Or who are you referring to?
It is not my main concern to be honest :)
Personally, I care more about the name being good by itself (when being used within the codebase, in responses, protocol names, etc) and less of why it is important now :D 
I wanted to list reasons that other people can hopefully relate to to get support for pushing for this now :)

**Comment by bonomat** [comment]
thought so :P

**Comment by tcharding** [comment]
Suggest we just use this thread and come up with a name instead of using a white board.  If we all add any terms that are relevant then any of us can do the rearranging and make suggestions.  As the newest, and one with the least domain knowledge, I'll kick it off.

**Comment by tcharding** [comment]
- Hashed Time Lock Contracts
- SHA-256
- two party
- Atomic
- Single round trip message requirement
- Non-custodial
- Token free
- On chain
- Linkable
- Large/verbose contract 
- Block time limited

**Comment by bonomat** [comment]
Imho an unambiguous name has to contain HTLC in it somehow. Everything else could be any (atomic swap) protocol.

**Comment by D4nte** [comment]
on chain HTLC
Layer 1 htlc

**Comment by tcharding** [comment]
> Layer 1 htlc

Is there any reason not to use these three words?  Does this clash with any near future protocols?

**Comment by bonomat** [comment]
Done in https://github.com/comit-network/spikes/pull/47
@da-kami & @thomaseizinger : please create follow-up tickets.
