### ISSUE TITLE
Design protocol for integrating LND into cnd

### ISSUE THREAD

**Issue by bonomat** [comit-network/RFCs#134]
# Problem

Doing an atomic swap with on-chain transactions is constrained by the underlying blockchain. This has several downsides:
* Transactions are bound to the blocktime. This means, an atomic swap between Bitcoin and Ethereum using on-chain transactions would take on average more than 20 minutes provided both parties are fine with 1 confirmation. 
* Transactions are _expensive_ and the fee needs to be calculated ad-hoc according to network congestions.
* The atomic swap is _traceable_ as both on-chain transactions include the same hash.

# Goal

Come up with a new protocol for adding support for LND in cnd.

**Comment by kilrau** [comment]
Check https://opendex.network/

**Comment by thomaseizinger** [comment]
So actually, I kind of scope-creeped https://github.com/comit-network/comit-rs/issues/1838 so the protocol is already part of that.

I am closing this issue in favor of https://github.com/comit-network/comit-rs/issues/1838.
