### ISSUE TITLE
RFC to specify Bitcoin asset

### ISSUE THREAD

**Issue by D4nte** [comit-network/RFCs#22]
Create RFC to specify the following Bitcoin related topics:
- HTLC and explanation
- Identity

Blocked by comit-network/comit-rs#679

**Comment by D4nte** [comment]
@comit-network/rust-devs please share your thoughts on how you saw this happening.

**Comment by bonomat** [comment]
It's for https://github.com/comit-network/RFCs/pull/34/files right? 
You've started off well already. Important is that if someone takes this RFC he knows exactly is supported at the moment. 
I like the way you've started already and added some comments in the PR.
