### ISSUE TITLE
Document RFC process (meeting notes)

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/RFCs#24]
- RFC0 documents RFC process
- README mentions the `status` of an RFC
- `Draft` RFCs have a discussion issue
- Discussion issues have a list of open questions/problems
- Once they are solved, a finalization PR is made
- This PR modifies the registry + changes status to `Final`

**Comment by LLFourn** [comment]
LGTM can we move this out of review?

**Comment by thomaseizinger** [comment]
Will be closed as soon as #28 is merged.
