### ISSUE TITLE
RFC to define BTC<->OmniLayer token swap (same chain)

### ISSUE THREAD

**Issue by D4nte** [comit-network/RFCs#36]
RFC to define new protocol that facilitates the exchange OmniLayer token assets with Bitcoin assets (same chain swap).

Please note that Omni**Coins** are just special OmniLayer tokens with a predefined token id so this RFC could mention them.
However, OmniLayer specifications already define a protocol for BTC<->OmniCoin.

This is for same chain swaps only. See #33 for cross-chain swaps using RFC-003.

See [comit-network/comit-rs#691](https://github.com/comit-network/comit-rs/issues/691) and [comit-network/comit-rs#772](https://github.com/comit-network/comit-rs/pull/772) for the highlight of the findings to know what to write in the RFC.

Child of [comit-network/comit-rs#663](https://github.com/comit-network/comit-rs/issues/663)

**Comment by D4nte** [comment]
@bonomat Shall we put that on hold?

**Comment by bonomat** [comment]
Closing this as currently not on the timeline and we will rewrite the issues when needed.
