### ISSUE TITLE
⚗️ Can RFC7 Ether HTLC be specified without knowing identities upfront

### ISSUE THREAD

**Issue by LLFourn** [comit-network/RFCs#40]
The Bitcoin and Ether HTLCs have different functionality. The Bitcoin HTLC lets you specify which identity will finally own the funds upon *redeeming* while the Ether HTLC makes you specify the final address at contract creation time.

By restructuring the Ether HTLC we may be able to give it this functionality and therefore ease the burden on implementations.

**Comment by LLFourn** [comment]
I just spent some time figuring out how you can verify a ECDSA signature on Ethereum. It's possible by abusing the `ecrecover` precompiled contract. This contract will return the *address* of the public key for which this signature is valid. So if you want to verify a signature under a public key you first get the address of the public key and check that it's equal to `ecrecover` on the "recoverable" signature.

The question then is what message to sign and how to produce the hash of it (`ecrecover` takes the hash as the argument not the message). We need domain separation so that it's impossible this signature could be reused for anything other than unlocking this particular contract and this particular swap.

**Comment by bonomat** [comment]
*I don't think it would be a misuse of the `ecrecover` contract - imho that's what is made for.

The following should give us the same experience as for bitcoin: 

* we embed the `redeem/refund_identity` in the contract (this is an ethereum address)
* the message to sign is the contract itself (we can load it with `codecopy`)
* this is then hashed (passed to the `SHA-256` precompiled contract or using `sha3` opcode)
* the redeemer/refunder needs provide this signature as input for redeeming/refunding and everything is passed to the `ecrecover` contract

The whole procedure might be quite expensive though: 
* loading contract code = `2 + 3 * (words copied)`
* sha-256 = `60 * 12 * (words)`
  * or for sha3= `30 + 6 * (words)`
* ecrecover = `3000`

--> words=256 bits=32 bytes

**Comment by LLFourn** [comment]
Signing the whole contract code could work but you need to sign the final redeem address to prevent front running. I think we should include the `networkid` and `chainid` in there to prevent replay attacks (though they are not very practical). We can replace the contract code with the contract address and just do:

```
redeem_hash = H(networkid || chainid || htlc_contract_address || final_redeem_address)
refund_hash = H(networkid || chainid || htlc_contract_address || final_refund_address)
```
The final addresses are passed in along with the signature on them in the redeem/refund transactions.

Since sha3 is cheaper there doesn't seem to be any reason to use sha256

**Comment by bonomat** [comment]
>  I think we should include the networkid and chainid in there to prevent replay attacks (though they are not very practical)

Can you explain the replay attack scenario you want to be protected against please? The ones I can think of are really not practical to protect against (e.g. after fork replay attack)

>  [...] `networkid` and `chainid`  [...]

I think there is an issue with including `networkid` and `chainid` in the message:
We will need to be able to generate the same message from within the contract (or embed it during deployment time). Afaik we can't get the `networkid` or `chainid` from within the contract, meaning we will need to embed this before. 
--> Using the `htlc_contract_address` as message to sign could be enough.

> The final addresses are passed in along with the signature on them in the redeem/refund transactions.

My assumption was that the message was signed from either the `redeem_identity` or `refund_identity`. 
Doing so, only one branch of the HTLC can be executed with a particular signature. 

> Since sha3 is cheaper there doesn't seem to be any reason to use sha256

Yes, correct. This will reduce the overall gas cost a bit :)
