### ISSUE TITLE
Should we use camelCase for all keys in JSON documents?

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/RFCs#59]
There is this idea to make the JSON encoding the default and thereby postpone all decisions about other encodings to a later point: https://github.com/comit-network/RFCs/issues/57

If JSON is the default, we might consider using a more JSON-idiomatic naming convention for all fields: camelCase.

**Comment by bonomat** [comment]
Closing as this optimization does not seems to be important enough. (:
