### ISSUE TITLE
Use asciiDoc instead of markdown

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/RFCs#61]
Use ascii doc for all templates so that it is default for future spikes and rfcs. 
Also, unify spike templates. 

- [x] https://github.com/comit-network/spikes/
- [x] https://github.com/comit-network/rfcs/
- [x] https://github.com/coblox/spikes/

**Comment by bonomat** [comment]
I like it. Just tried it out in comit-network#6.

**Comment by thomaseizinger** [comment]
Did you reference the correct issue? I cannot really follow :)

**Comment by LLFourn** [comment]
Closed wtth https://github.com/comit-network/RFCs/pull/67
