### ISSUE TITLE
How should the Ethereum HTLC react to invalid invocations?

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/RFCs#62]
There are two ways of invoking the Ethereum HTLC in an invalid way:

- with the wrong secret
- without the secret but before the expiry

In both cases, we currently `return` from the contract without doing anything. This makes it hard to observe, whether or not the invocation was actually successful. From an EVM perspective, it executes successfully (i.e. without any errors)
Such an observation would be useful in numerous ways:
1. In our e2e tests to check if the refund actually worked or if we have to invoke it again
2. Metamask may show something different if the user invokes a refund too early. Showing a successful transaction if it actually was not successful is pretty misleading.

---

Ethereum has the `revert` instruction to halt execution of a contract and rollback any changes.

This spike is about investigating, what the best way is to _fail_ the invoking transaction of the HTLC.

**Comment by D4nte** [comment]
Added info: currently it not clear why the contract fail when it fails. Wrong secret? Too early?
It *might* be interested to consider logging on failure.
