### ISSUE TITLE
Writeup RFC for bam over libp2p

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/RFCs#65]
Deprecate BAM!, rename the RFC to "COMIT messages" to specify headers, encoding by default using JSON, usage of libp2p and substream management.

Related to #57 

DoD:
- [ ] RFC001 is re-written
- [ ] RFC-001-BAM label on GitHub is renamed
- [ ] Check/re-write BAM section in RFC-002
- [ ] Check other BAM mentions in `README.md` and `registry.md`
- [ ] Make sure to mention assumptions about the libp2p-stack (TcpTransport, Yamux multiplexer, Secio encryption)
- [ ] Make sure the `Error` frame was removed as part of this process to align with #117

**Comment by D4nte** [comment]
@thomaseizinger all boxes done? (not ticked)

**Comment by thomaseizinger** [comment]
> @thomaseizinger all boxes done? (not ticked)

Nope :sweat_smile:
