### ISSUE TITLE
Change `α` to `alpha` in RFC003

### ISSUE THREAD

**Issue by bonomat** [comit-network/RFCs#68]
Currently, RFC-003-SWAP-Basic uses the notion `α`. 
However, while I like the short form of `α` instead of `alpha` I think we should use `alpha` everywhere, because:

* we don't use this notion in any other RFC -> this would keep all RFCs aligned
* `alpha` is easier to write - I would not know how to write an `α` on my keyboard without googling it
* I think it is a bit weird to mix `alpha` and `α` --> e.g. we have `alpha HTLC` and `α-HTLC`

**Comment by thomaseizinger** [comment]
Added mid-sprint because it allows me to resolve #114.
