### ISSUE TITLE
Remove hyphen from "RFC-003" when present

### ISSUE THREAD

**Issue by tcharding** [comit-network/RFCs#77]
DoD:
The following commands return 0 when executed in all coblox & comit-network repositories.
- `$ git grep -i 'rfc-00[0-9]' | wc -l`

**Comment by D4nte** [comment]
I thing we should jump directly into the core of the debate: shouldn't we use "basic-swap" everywhere instead?

**Comment by tcharding** [comment]
Agreed, that is the core of the debate.  I'm shy on the word 'basic'.  Generally, IMO, it is bad practice to name things with subjective terms like 'basic' since these inevitable change as time goes on.  A more concrete name would fair better as the project matures.  'basic-swap' is swap between two ledgers with certain characteristics (or requirements), right?.  Can we name these?  Can we come up with a protocol name that includes/describes these requirements?

**Comment by D4nte** [comment]
After talking with Daniel I propose "Basic HTLC Atomic Swap".
Alternative I could see: "Simple HTLC Atomic Swap" (but I guess it does not help).

Happy to discuss more with you/team to find a better terminology.

**Comment by bonomat** [comment]
We plan to rename RFC003: I propose removing the hyphen while doing #130
