### ISSUE TITLE
RFC structure improvement

### ISSUE THREAD

**Issue by da-kami** [comit-network/RFCs#79]
After several discussions with @tcharding on the RFCs I would like to propose some changes to the RFC repository to make COMIT more understandable. 

Most important, I'd propose to adapt the README of the RFC repository. This is the first point of entry for people trying to understand COMIT and it does not explain anything. 

Currently the RFCs are a flat list and one cannot easily understand what is going on there without having the hierarchy lined out in e.g. the README. The more ledgers we add the more difficult it will get to stay on track with the hierarchy. Especially once adding lightning this will get messy, as we introduce another protocol on hierarchy level 3 and not just ledger-implementations for the existing RFC003 (which is on level 3)
We could think about introducing a folder structure to have more hierarchy. 

Proposed structure after discussion with @D4nte:
```
- Messaging in COMIT (network communication) 
   - RFC-001-BAM.md (might be replaced with libp2p)
- Ledgers & Assets definitions
   - RFC-004-Bitcoin.md
   - RFC-006-Ethereum.md
   - RFC-008-ERC20.md
- Protocol Families
   - RFC-002-SWAP.md
- SWAP Protocols
   - Atomic Swaps using HTLCs ["basic" is still in debate]
      - RFC-003-SWAP-Basic.md
      - Implementation Details for SWAP Basic
         - RFC-005-SWAP-Basic-Bitcoin.md
         - RFC-007-SWAP-Basic-Ether.md
         - RFC-009-SWAP-Basic-ERC20.md
```

Dropped DoD:
- ~~Introduce structure as folder structure and sort in files~~: good idea but we may change structure so let's do it once we have more RFCs and the categories are stable.
- ~~Remove protocol specifics from the examples in "Ledger & Asset definitions"~~: real examples are better

Agreed DoD:
- [ ] Introduce structure in README

**Comment by D4nte** [comment]
> ❓ Why was the ledger and implementation detail information split up (i.e. why is RFC004 and RFC005 not in the same file)?

Because one RFC is about introducing the basic definition for the given ledger. Another RFC is about defining basic swaps.

**Comment by da-kami** [comment]
> > ❓ Why was the ledger and implementation detail information split up (i.e. why is RFC004 and RFC005 not in the same file)?
> 
> Because one RFC is about introducing the basic definition for the given ledger. Another RFC is about defining basic swaps on the ledger.
> We find it cleaner this way.

So RFC004 specifies the details of RFC002 for Bitcoin and RFC005 specifies the details of RFC003 for Bitcoin? Or are both RFC004 and RFC005 specifying details for RFC003?

**Comment by D4nte** [comment]
> 💡 The thoughts from above lead to the conclusion that it could help to separate the asset from the "ledger".

Yes, the ledger is separated from the asset.
Ledgers: Ethereum, Bitcoin blockchain, Lightning Network, Liquid Network
Assets: Ether, ERC20 token, Bitcoin

From "🤔 Here are some more of my thoughts - hopefully this can spark helpful discussion:" and below, you are in line with what we think.

**Comment by D4nte** [comment]
> So RFC004 specifies the details of RFC002 for Bitcoin and RFC005 specifies the details of RFC003 for Bitcoin
Correct

**Comment by da-kami** [comment]
> > 💡 The thoughts from above lead to the conclusion that it could help to separate the asset from the "ledger".
> 
> Yes, the ledger is separated from the asset.
> Ledgers: Ethereum, Bitcoin blockchain, Lightning Network, Liquid Network
> Assets: Ether, ERC20 token, Bitcoin
> 
> From "🤔 Here are some more of my thoughts - hopefully this can spark helpful discussion:" and below, you are in line with what we think.

I don't think so - I am proposing to remove the ledger from the SWAP protocol and specify it one level down in the hierarchy. (i.e. remove alpha and beta ledger from SWAP...). I am not sure it is a good idea - I just tried to find out what bugged me with the way we add lightning and think about the protocol in general 😄

**Comment by D4nte** [comment]
Propose structure:

```
- Messaging in COMIT (network communication): RFC-001-BAM.md (might be replaced with libp2p)
- Ledgers & Assets definitions:
   - RFC-004-Bitcoin.md
   - RFC-006-Ethereum.md
   - RFC-008-ERC20.md
- Protocol Families
   - RFC-002-SWAP.md
- SWAP Protocols
   - RFC-003-SWAP-Basic.md
   - Implementation Details for SWAP Basic
        - RFC-005-SWAP-Basic-Bitcoin.md
        - RFC-007-SWAP-Basic-Ether.md
        - RFC-009-SWAP-Basic-ERC20.md
```

**Comment by da-kami** [comment]
@D4nte I updated the issue description and added a Dod. Minor modification of your proposed structure here: 
```
...
- SWAP Protocols
   - SWAP Basic - Atomic Swaps using Basic HTLCs
      - RFC-003-SWAP-Basic.md
...
```

Won't do changes until groomed 😉

**Comment by D4nte** [comment]
I wouldn't not remove the numering in file names but rename to "Basic HTLC Atomic Swap"

**Comment by tcharding** [comment]
> I wouldn't not remove the numering in file names

+1

> but rename to "Basic HTLC Atomic Swap"

This is linked to https://github.com/comit-network/RFCs/issues/77

As stated on that issue I don't like the use of subjective terms like 'basic', they are at risk of becoming stale, we also need a variable name and a string to send over the wire based on this title.

**Comment by D4nte** [comment]
> As stated on that issue I don't like the use of subjective terms like 'basic', they are at risk of becoming stale, we also need a variable name and a string to send over the wire based on this title.

"Basic" makes sense to me, happy to discuss more with you/team.

**Comment by bonomat** [comment]
@bonomat=stalbot: 

old and untouched.
