### ISSUE TITLE
Incorrect terminology 'transport protocol'

### ISSUE THREAD

**Issue by tcharding** [comit-network/RFCs#83]
RFC-001 contains the following sentence under heading 'Motivation and Requirements' (bold text highlights the terminology in question:

> In COMIT, nodes need to exchange all kinds of information in a peer-to-peer manner. As COMIT is an inherently distributed system, the network will eventually become heterogeneous, with an array of implementations, varying in languages and versions. Given that, we need a **transport protocol** that fulfils the following requirements:

'transport protocol' is defined [here](https://encyclopedia2.thefreedictionary.com/transport+protocol) as:
> A communications protocol responsible for establishing a connection and ensuring that all data has arrived safely. It is defined in layer 4 of the OSI model. Often, the term transport protocol implies transport services, which includes the lower-level data link protocol that moves packets from one node to another.

BAM is _not_ a transport protocol.  It is an application layer protocol.

**Comment by D4nte** [comment]
@tcharding in this cases, I personally think it's more efficient to just open the PR :)

**Comment by tcharding** [comment]
Point noted @D4nte, thanks.
