### ISSUE TITLE
RFC example JSON does not match comit-rs

### ISSUE THREAD

**Issue by tcharding** [comit-network/RFCs#84]
JSON in RFC-002 and RCF-003 does not match the scheme in `api_tests/swap.scheme.json`.  This is a discussion topic because we should decide which is the single point of truth (SPOT).

**Comment by D4nte** [comment]
This is expected.
- RFC-002/RFC-003: this is the BAM!/libp2p messages exchanged between 2 comit_nodes
- `api_tests/swap.scheme.json` this is the REST API exposed by `comit-rs` to be consumed by clients such as `comit-i` and `bobtimus`.

**Comment by tcharding** [comment]
Oh poo
