### ISSUE TITLE
Frame "type" (REQUEST/RESPONSE/ERROR) and payload "type" (SWAP/…) is misleading

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/RFCs#96]
The use of the key `type` on two different layers, FRAME and REQUEST is confusing.
Can we come up with a different structure or a different name for any one of the two in order to unambiguously refer to these keys?

**Comment by tcharding** [comment]
Massive +1 from me!

**Comment by thomaseizinger** [comment]
#121 is kind of accepted. With it, the concept of frame types and request types is removed.
